uploading the ADOR Boston version of feelingrestful theme.
humanmade/feelingrestful-theme pull request #56
Opened 2017-01-11 12:00 UTC by missjwo

To be tagged as Version 2.

2017-01-12 01:03 UTC, tareiking requested changes
Thanks @missjwo, changes requested. But largely, looks good.

Could do with a 'getting started' guide if we are open sourcing the theme, as there are a few requirements for the project build, so users couldn't just compile the theme and have it work out of the box.

Let me know if you would like some help there :)

2017-01-12 01:03 UTC, tareiking commented on .gitignore
> +.idea
CS: Needs line break on EOF.

2017-01-12 01:03 UTC, tareiking commented on inc/menu-api.php
> +
Docblock: Missing docblock here, not sure what our stance is with required docs on this release. But just raising it here.

2017-01-12 01:03 UTC, tareiking commented on index.php
> +	<script src="https://maps.googleapis.com/maps/api/js&key=<?php if ( defined( 'HM_GOOGLE_API_KEY' ) ) echo HM_GOOGLE_API_KEY ?>"></script>
Does this need a generic constant name for opensource projects?

2017-01-12 01:03 UTC, tareiking commented on index.php
> +<noscript><p style="color: black;">A Day of Rest Boston is built in JavaScript. If you are reading this message it means
Should i18n this string.

2017-01-12 01:03 UTC, tareiking commented on js/actions.js
> +export function fetchMenubyLocation( location = 'primary_navigation' ) {
Should be `fetchMenuByLocation`, but not a blocker.

2017-01-12 01:03 UTC, tareiking commented on js/components/Preview.jsx
> +} )
Missing extra line at EOF.

2017-01-12 01:03 UTC, tareiking commented on js/components/modules/SponsorsDetail.jsx
> +													                                  target="_blank"><img
Spacing here a a little curious. Could be tidied up.

2017-01-12 01:03 UTC, tareiking commented on js/components/modules/TestimonialSlider.jsx
> +												  <span className="byline">, <a
CS: Spacing here. `a` tag could drop to next line?

2017-01-12 01:03 UTC, tareiking commented on js/components/modules/Workshops.jsx
> +		return (
@missjwo - Are workshops not stored as CPTs? This seems to be the only static content in the theme.

2017-01-12 01:03 UTC, tareiking commented on js/components/pages/Page.jsx
> +
CS: Can remove extra line here.

2017-01-12 01:03 UTC, tareiking commented on js/components/pages/Speaker.jsx
> +					<div className="loading"><span className="fa fa-heart"></span> Loading</div>
Just a thought: After seeing a few of the `.loading` wraps, this could be a separate react module instead. Not a blocker.

2017-01-12 01:03 UTC, tareiking commented on js/components/pages/Workshop.jsx
> +
CS: Can remove extra line here.

2017-01-12 18:43 UTC, missjwo commented on .gitignore
> +.idea
👍

2017-01-12 18:48 UTC, missjwo commented on index.php
> +	<script src="https://maps.googleapis.com/maps/api/js&key=<?php if ( defined( 'HM_GOOGLE_API_KEY' ) ) echo HM_GOOGLE_API_KEY ?>"></script>
I dont think so. its a HM project and multimatley. there is HM_DEV in places too.

2017-01-12 18:51 UTC, missjwo commented on inc/menu-api.php
> +
+1

2017-01-12 18:51 UTC, missjwo commented on inc/menu-api.php
> +
👍

2017-01-12 18:52 UTC, missjwo commented on js/actions.js
> +export function fetchMenubyLocation( location = 'primary_navigation' ) {
👍

2017-01-12 18:52 UTC, missjwo commented on js/components/Preview.jsx
> +} )
👍

2017-01-12 21:56 UTC, missjwo commented on js/components/modules/SponsorsDetail.jsx
> +													                                  target="_blank"><img
👍

2017-01-12 21:57 UTC, missjwo commented on js/components/modules/TestimonialSlider.jsx
> +												  <span className="byline">, <a
👍

2017-01-12 21:58 UTC, missjwo commented on js/components/modules/Workshops.jsx
> +		return (
No they ain't at the moment.

2017-01-12 21:59 UTC, missjwo commented on js/components/pages/Page.jsx
> +
👍

2017-01-12 21:59 UTC, missjwo commented on js/components/pages/Speaker.jsx
> +					<div className="loading"><span className="fa fa-heart"></span> Loading</div>
Thats true but i think its out of scope for this.

2017-01-12 22:00 UTC, missjwo commented on js/components/pages/Workshop.jsx
> +
👍

2017-01-12 22:46 UTC, missjwo commented on index.php
> +<noscript><p style="color: black;">A Day of Rest Boston is built in JavaScript. If you are reading this message it means
Yes, although im struggling to work out what the best way to i8n it is. There are two paragraphs on that line so it should be two strings to translate but. the URLs in the middle of them is making me :/. about it all.

2017-01-12 22:48 UTC, missjwo commented
@tareiking  did most of  the suggestions. The EOL stuff doesnt show up as outdated as its after the comments. You have to click into the file to actually see the extra lines. 

Just struggling with the i8n comment and then i think. its good to go.

2017-01-13 11:57 UTC, missjwo commented
Fixed up the i8n too. 

Should be ready to go.

2017-01-15 22:58 UTC, tareiking approved these changes

2017-01-15 22:58 UTC, tareiking commented
@missjwo nice work on the i18n! Looks good to me, thanks for all your hard work!

2017-01-15 23:02 UTC, merged